// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlavhiebuhsqzhosivzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYXZoaWVidWhzcXpob3NpdnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ4MjAsImV4cCI6MjA2OTM3MDgyMH0.F_4nyBMtPeMMovArlk9rgtfKsE1MIk2C39j8gfTs_YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});